### ISSUE TITLE
i want to use jetson NX

### ISSUE THREAD

**Issue by fukaura** [stereolabs/zed-ros2-wrapper#10]
Hi, i want to run zedm on jetson NX.
Only jetpack4.4 support jetson NX.
So, i need to install ZED SDK3.2.

When does zed-ros2-wrapper support for ZED SDK 3.2?

**Comment by Myzhar** [comment]
The new ROS2 wrapper supporting ZED SDK v3.3 and ROS2 Eloquent has been released
