### ISSUE TITLE
"sl" package missing?

### ISSUE THREAD

**Issue by nickgoberville** [stereolabs/zed-ros2-wrapper#11]
Getting errors like:

1) error: no matching function for call to ‘sl::Camera::enableRecording(const char*, sl::SVO_COMPRESSION_MODE&)’
2) error: ‘SVO_COMPRESSION_MODE_RAW’ is not a member of ‘sl’
3) error: ‘SUCCESS’ is not a member of ‘sl’
4) etc...

when executing: "colcon build --symlink-install --packages-select stereolabs_zed --cmake-args=-DCMAKE_BUILD_TYPE=Release"

How do I fix this?

**Comment by Myzhar** [comment]
Hi @nickgoberville 
The ROS2 wrapper does not yet work with SDK v3.x.
You must use SDK 2.8.5. You can download it here:
https://www.stereolabs.com/developers/release/2.8/

We will update the ROS2 wrapper to support the ZED SDK v3.x and the latest ROS2 version in the next few months.

**Comment by nickgoberville** [comment]
Thank you!
