### ISSUE TITLE
ZED components does not build with ROS2 humble

### ISSUE THREAD

**Issue by JAP3TH** [stereolabs/zed-ros2-wrapper#110]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

We receive an error of `zed_components` during the colcon build process. For me, it looks as if the type `SENSOR_WORLD` is not declared in the `sl` library which apparently comes with the ZED SDK.

### Steps to Reproduce

We use the ZED SDK in a tailored docker. We cloned the `zed_components` in our container environment to build it with colcon after the docker with CUDA, ZED SDK and other stuff succeeded to build. We checked out the `ros2_humble` branch of `zed_ros2_wrapper` to let it run with our ROS2 Humble installation in our docker.

### Expected Result

During `colcon build`, the zed_components package builds successfully.

### Actual Result

During `colcon build`, the zed_components package build process fails with an error.

`‘sl::SENSOR_WORLD’ has not been declared` and similar errors related to `sl::SENSOR_WORLD`.

![Screenshot from 2022-10-21 16-40-59](https://user-images.githubusercontent.com/79508077/197222817-b3f8a1f3-db9c-4f30-8dc0-965f47fe8c41.png)

### ZED Camera model

ZED2

### Environment

```shell
OS: Ubuntu 22.04
ROS2 Version: humble
Python 3.10
ZED SDK: 3.8.0 for CUDA 11.7

zedsdk/pyzed installed.
```

**Comment by Myzhar** [comment]
Hi @JAP3TH 
you must update the wrapper to the latest `master`.
We just released the official support for ROS2 Humble (a few minutes after you opened this issue).
