### ISSUE TITLE
ROS Eloquent - ZED_compoenet build error

### ISSUE THREAD

**Issue by harisiva1** [stereolabs/zed-ros2-wrapper#12]
![Screenshot from 2020-09-12 11-02-50](https://user-images.githubusercontent.com/68550704/94020856-ac4e3000-fdb3-11ea-8339-77381c8c6ae4.png)
Hello,
I get an std error(please see the attached image) for zed_component while trying to build the package in ros eloquent.Could you please support?

Also i don't see any node or launch files to view camera output in rviz. When is it expected to release here / any release planned?

Thanks in advance !

Regards,
Hari.s

**Comment by Myzhar** [comment]
Hi @harisiva1 
the Eloquent branch is under active development and it has not yet been officially released in a stable version

However your problem seems related to CUDA that has not been correctly installed in your system.

About RVIZ, currently we have not yet added a launch file for it because we are adding new features continuously and we are simply manually starting RVIZ using the `rviz2` command and we are selecting to view only the topic that are under testing.

**Comment by harisiva1** [comment]
Hi,
Thanks for your quick reply.
yeah it was a problem with CUDA, "libnppicom.so" seems to be missing in CUDA 11 for Ubuntu 18.

So i tried with CUDA10.2  and corresponding ZDK version in ros eloquent.It was build successfully however with many warnings and atlast stderr output(zed_compoenent).
Please see the attached image.

I am waiting for the stable version release for eloquent.
Thanks for the update!

![Screenshot from 2020-09-10 12-47-59](https://user-images.githubusercontent.com/68550704/94022954-ee787100-fdb5-11ea-9097-08ba95d57ff1.png)
![Screenshot from 2020-09-10 12-48-31](https://user-images.githubusercontent.com/68550704/94022970-f3d5bb80-fdb5-11ea-8814-e80483ead1d4.png)

**Comment by Myzhar** [comment]
OK, you can ignore those warnings. If you compile forcing the Release mode they will disappear:
`colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release`

The main functionalities of the node are working: image,depth,pointcloud,positional tracking, TF, dynamic parameters.
We are currently working to add sparial mapping and object detection support

**Comment by harisiva1** [comment]
hello,
i am unable to find and run nodes which gives image,depth and point cloud etc., in eloquent.can you support me?

**Comment by Myzhar** [comment]
The release for ROS2 Eloquent has not yet been merged into `master` branch. 
It is yet under development and you can get latest version checking out the `eloquent` branch and recompiling. 
As it is yet under active development it may change daily before the merging into `master`.

**Comment by Myzhar** [comment]
To start the node you can follow the instructions in the README file:
https://github.com/stereolabs/zed-ros2-wrapper/tree/eloquent#starting-the-zed-node

**Comment by harisiva1** [comment]
i checked out eloquent branch but i dont see "zed_wrapper" package in my system.so i am not launch zed launch file.
are there some command line to sync it?

**Comment by Myzhar** [comment]
Have you followed the installation instruction in the README?
https://github.com/stereolabs/zed-ros2-wrapper/tree/eloquent#build-the-package

I add here the steps to clone the `eloquent` branch:
```
$ cd ~/ros2_ws/src/ #use your current ros2 workspace folder
$ git clone https://github.com/stereolabs/zed-ros2-wrapper.git
$ cd zed-ros2-wrapper
$ git checkout eloquent
$ cd ../..
$ rosdep install --from-paths src --ignore-src -r -y
$ colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release
$ echo source $(pwd)/install/local_setup.bash >> ~/.bashrc
$ source ~/.bashrc
```

**Comment by harisiva1** [comment]
git pull resolved my previous issue.
now i am able to launch the file but i don't see the topics like rect_image_raw ,cloud_point registered etc., in eloquent..so it is still under development right?

**Comment by Myzhar** [comment]
Many topic names are changes to match the names used in ROS1.
You can see the full list of available topics with the command:
`$ ros2 topic list` or using RQT

**Comment by harisiva1** [comment]
yes i have looked at all the topic earlier using the cmd as you said above and neither zed is turning on(no light in zed camera) nor i can see the image(camera output,depth image,confidence image etc.,) in rviz after i launch the launch file and zed node.

**Comment by Myzhar** [comment]
You can use rqt or rviz2 to view topics

![Screenshot from 2020-10-10 16-08-26](https://user-images.githubusercontent.com/3648617/95657081-df622480-0b12-11eb-833f-374f4f9e31b7.png)

**Comment by harisiva1** [comment]
are the above images from rviz in **eloquent**?

**Comment by Myzhar** [comment]
They are

**Comment by harisiva1** [comment]
please support me..
![Screenshot from 2020-10-10 16-22-47](https://user-images.githubusercontent.com/68550704/95657488-03bf0080-0b15-11eb-8552-26be3bf52f97.png)

**Comment by Myzhar** [comment]
You cannot find any topic because the node is not running. 
If you read carefully the console log you can see that the lib file `libnvcuvid.so.1` is missing. This means that you have not correctly installed CUDA on your machine. 
Can you run the zed tools? Try for example `ZED_Depthviewer`

**Comment by Myzhar** [comment]
@harisiva1 can you close this issue if you solved it?

**Comment by harisiva1** [comment]
hi,
sorry for the late reply!
it has already worked me weeks ago ,so you can consider this issue as closed

**Comment by harisiva1** [comment]
Hi,
Which topic do i need to choose to create mapping in rviz?
