### ISSUE TITLE
wrapper won't build within nvidia supplied Hubmle container

### ISSUE THREAD

**Issue by AndreV84** [stereolabs/zed-ros2-wrapper#129]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

how to change installation path?
due to some reason the default path used by installer is not available in nvidia Humble supplied container

### Use-Case

which results in fault trying to installing sdk within the container
```
Installing...
Installation path: /usr/local/zed
Checking CUDA version...
OK: Found CUDA 11.4
cp: cannot create directory '/usr/local/zed/tools': Permission denied
find: ‘/usr/local/zed/tools/’: No such file or directory
```

### Anything else?

I am trying to get nvblox container to show zed outputs
;it has been a while due to lack of support from both providers

**Comment by Myzhar** [comment]
@AndreV84 I'm sorry, but this is not a bug or a feature request. 
For this kind of support requests kindly ask on the Stereolabs forum.
Gitlub issues must be used to report a bug or ask for new features.
