### ISSUE TITLE
Unknown CMake command "rclcpp_register_node_plugins"

### ISSUE THREAD

**Issue by AbeLiuXL** [stereolabs/zed-ros2-wrapper#14]
Unknown CMake command "rclcpp_register_node_plugins"

**Comment by Myzhar** [comment]
Hi @AbeLiuXL 
You are trying to compile the master branch with a ROS2 release that is not Crystal. 
We are working on a new release of the wrapper for ROS2 Eloquent. You can test it in the `eloquent` branch, but it is not yet completed and it is changing daily.

**Comment by Myzhar** [comment]
Fixed with Eloquent release
