### ISSUE TITLE
Launching multiple cameras in ros2 

### ISSUE THREAD

**Issue by ArghyaChatterjee** [stereolabs/zed-ros2-wrapper#147]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

I can't see a ros2 launch file for multiple camera launch. I have a zed2 and a zed mini and I am trying to launch them both as ros 2 nodes in ubuntu 22.04 and zed sdk 4.0. when I try to launch 2 separate launch files for zed2 and zedmini, the computer can detect one but not the other. Specially the one which were launched later are saying camera can not be detected. Please do something asap. I need it early with ros2 support. Thanks.

### Use-Case

ROS2 related multl-zed-camera launching

**Comment by Myzhar** [comment]
@ArghyaChatterjee I transferred the issue in the correct repository. 
However, this is not an issue, the feature that you are searching for already exists:
https://github.com/stereolabs/zed-ros2-examples/tree/master/tutorials/zed_multi_camera
