### ISSUE TITLE
How optimize AI model once

### ISSUE THREAD

**Issue by rafal-gorecki** [stereolabs/zed-ros2-wrapper#151]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Hi,
I create docker with zed-ros2-wrapper (based on yours solution) and i wonder how to disable, build docker, or add volumen to eliminate every time optimization. Do you have any solutions?

**Comment by Myzhar** [comment]
Hi @rafal-gorecki 
the reply is in the README in the `docker` folder:
https://github.com/stereolabs/zed-ros2-wrapper/tree/master/docker#ai-module

**Comment by Myzhar** [comment]
@rafal-gorecki please close the issue if solved

**Comment by rafal-gorecki** [comment]
Thank you!
