### ISSUE TITLE
Black stripes in depth image

### ISSUE THREAD

**Issue by jungjjang44** [stereolabs/zed-ros2-wrapper#153]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi, I'm trying to make sure that zed2's depth camera works well in the ros2 environment. However, there was a problem that the depth image did not come out properly. At first, I thought it was a problem with the camera itself, but the depth viewer confirmed that it was running well. ros2 launch zed_wrapper zed2.launch.This is the picture that appears when you run py and receive the /zed2/zed_node/depth_registered topic from rviz2. How do we solve these problems?
![Screenshot from 2023-05-15 15-05-21](https://github.com/stereolabs/zed-ros2-wrapper/assets/93628007/666cf81b-47ae-4e58-b19e-9e3dcec3c84b)

### Steps to Reproduce

1. ros2 launch zed_wrapper zed2.launch.py
2. rviz2
3. topic : /zed2/zed_node/depth/depth_registered

...

### Expected Result

Depth image outputs normally

### Actual Result

Black stripes in depth image

### ZED Camera model

ZED2

### Environment

```shell
OS : ubuntu 20.04
GPU : NVIDIA GeForce 1060 Ti
ROS_DISTRO : foxy
cuda version : 11.4
```

**Comment by Myzhar** [comment]
Hi @jungjjang44 
this is a ZED SDK installation issue. It's not a ZED ROS 2 Wrapper bug.
Please write an email to support@stereolabs.com and add the report file generated by the ZED Diagnostic tool as an attachment.
