### ISSUE TITLE
ZEDx Xacro cam pose arguments error

### ISSUE THREAD

**Issue by aaraujo11** [stereolabs/zed-ros2-wrapper#159]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

By adding the cam pose to the [zedx.launch.py](https://github.com/stereolabs/zed-ros2-wrapper/blob/master/zed_wrapper/launch/zedx.launch.py#L34), it cause an error related with Xacro command.

### Steps to Reproduce

1. Add the cam pose as a str (e.g. "0.1, 0.2, 0.3, 0, 0, 0" ) to the [zedx.launch.py](https://github.com/stereolabs/zed-ros2-wrapper/blob/master/zed_wrapper/launch/zedx.launch.py#L34). 
2. Launch zedx.launch.py

### Expected Result

Launch the ZEDx camera launch file as it launch without any issue, if i do not add the cam_pose param.

### Actual Result

`File "/opt/ros/foxy/lib/python3.8/site-packages/launch/substitutions/command.py", line 116, in perform
    raise SubstitutionFailure(f'executed command failed. Command: {command_str}')
launch.substitutions.substitution_failure.SubstitutionFailure: executed command failed. Command: xacro /home/nvidia/ros2_ws/install/zed_wrapper/share/zed_wrapper/urdf/zed_descr.urdf.xacro camera_name:=zedx camera_model:=zedx base_frame:=base_link gnss_frame:= cam_pos_x:=0.1 cam_pos_y:= 0.2 cam_pos_z:= 0.3 cam_roll:= 0 cam_pitch:= 0 cam_yaw:= 0`

### ZED Camera model

ZED

### Environment

```shell
Jetson AGX Orin 32GB
L4T: 35.2.1
Jetpack: 5.1
OS: Ubuntu 20.04
Release: 5.10.104-tegra
CUDA: 11.4.315
ROS2: Foxy
ROS foxy Xacro installed: ros-foxy-xacro 2.0.7-1
```

### Anything else?

Otherwise if for example i consider only a cam_pose_x, it generates the xacro without any issue. The xacro version i have installed is  ros-foxy-xacro 2.0.7-1After debug by executing xacro command isolated, i notice the issue is once you pass as argument more then one cam_pose_*, it gives the error:

`xacro /home/nvidia/ros2_ws/install/zed_wrapper/share/zed_wrapper/urdf/zed_descr.urdf.xacro camera_name:=zedx camera_model:=zedx base_frame:=base_link cam_pos_x:=0.1 cam_pos_y:= 0.2
Usage: xacro [options] <input>
xacro: error: expected exactly one input file as argument
`

**Comment by Myzhar** [comment]
Hi @aaraujo11 
the launch parameter `cam_pos_x` does not exist anymore starting from the version v4 of the Wrapper. You must set the pose of the camera as an array by using the `cam_pose` parameter: e.g. `cam_pose:=[0.1,0.2,0.0,0.0,0.0,0.0]`

You can get more information about the launch parameters by using the command 
`ros2 launch zed_wrapper zedx.launch.py -s`

```
[...]
    'cam_pose':
        Pose of the camera with respect to the base frame (i.e. `base_link`): [x,y,z,r,p,y]. Note: Orientation in rad.)
        (default: '[0.0,0.0,0.0,0.0,0.0,0.0]')
```

**Comment by aaraujo11** [comment]
Hello @Myzhar, solved thank you!
