### ISSUE TITLE
No GPU Detected

### ISSUE THREAD

**Issue by sandipsharan** [stereolabs/zed-ros2-wrapper#178]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hello, 

I'm trying to use the Dockerfile given in the zed-ros2-wrapper repository and build image to run the zed2.launch.py but it pops and error mentioning that no NVIDIA GPU is detected(Given in the 1st image). Tried changing the base image of the file and the arguments L4T_MAJOR and L4T_MINOR from 35.1.0 to 32.7.1 as my L4T version is 32.6.1 but it again threw an error. The error log is given below in the attached 2nd image

My L4T Version:  # R32 (release), REVISION: 6.1

### Steps to Reproduce

1. Git clone the zed-ros2-wrapper repo
2. Go into the docker directory in the package and build the image after mentioning the above changes given in the description using the command 
docker build -t <image_name> -f Dockerfile.l4t35_1-humble-release .
...

### Expected Result

Successfully running the launch file 

### Actual Result

Error mentioning No GPU detected
![Screenshot 2023-08-10 221543](https://github.com/stereolabs/zed-ros2-wrapper/assets/73119056/6fc36088-fd2f-409a-a99b-9c3bf093d38d)
![Screenshot 2023-08-11 192353](https://github.com/stereolabs/zed-ros2-wrapper/assets/73119056/166c627b-df38-49c2-b305-9db88ace1421)

### ZED Camera model

ZED2

### Environment

```shell
OS: Ubuntu 18.04
CPU: ARM
GPU: Jetson nano's integrated GPU
```

**Comment by Patrick-AA** [comment]
Hello, to use docker you have to make all the image version match your OS version.

Then when running the image you have to use a command similar to:
```
docker run --runtime nvidia -it --privileged --ipc=host --pid=host -e DISPLAY \
  -v /dev/shm:/dev/shm -v /tmp/.X11-unix/:/tmp/.X11-unix \
  -v ${HOME}/zed_docker_ai/:/usr/local/zed/resources/ \
  <image_tag>
```
