### ISSUE TITLE
IMU-Camera TF Broadcasting

### ISSUE THREAD

**Issue by anath93** [stereolabs/zed-ros2-wrapper#180]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

IMU Camera TF broadcasting even if publish_tf is disabled, I have posted in community page of stereolabs.

Link: [Click here](https://community.stereolabs.com/t/zed2i-imu-transform-to-add-to-robot-urdf/3009/12)

### Steps to Reproduce

1. Cleared the workspace and tried rebuilding the colcon workspace.
2. Set publish_tf and imu_tf to false but still getting published
3. When my Robot State publisher publishes, it causes problem as Zed is trying to publish and I am too with my robot urdf. 
4. But once disabled on my robot urdf, and enabled on zed side, it works fine, but still when disabled, it publishes the tf.
...

### Expected Result

When publish_tf is disabled, IMU tf should not be displayed, otherwise I will not be able to add this to my robot URDF.

### Actual Result

.

### ZED Camera model

ZED2i

### Environment

```shell
Ubuntu 20.04, Foxy, Nvidia Orin NX 64 GB
```

**Comment by Myzhar** [comment]
IMU TF and localization TF are separate.
You can disable IMU TF by setting this to false
            
`publish_imu_tf: true # [usually overwritten by launch file] enable/disable the IMU TF broadcasting`
it's also a launch parameter

**Comment by anath93** [comment]
I did that, if you refer to my screenshot in community link page, it still publishes it .

https://community.stereolabs.com/t/zed2i-imu-transform-to-add-to-robot-urdf/3009/12

**Comment by anath93** [comment]
@Myzhar Any update on this thread ?

**Comment by Myzhar** [comment]
@anath93 the behavior currently reflects the value of the `publish_tf` launch parameter, thus you cannot disable the broadcasting of the IMU TF if odometry TF is active.
I'm merging a fix that will add a new launch parameter for this.
Example: `$ ros2 launch zed_wrapper zed2i.launch.py publish_imu_tf:=False`

**Comment by anath93** [comment]
@Myzhar, I will try out the fix once out and close this issue once I have verified. Thank you !

**Comment by anath93** [comment]
@Myzhar, I am still getting imu_tf being published somehow. Cleared workspace and did colcon build but still same, 

![image](https://github.com/stereolabs/zed-ros2-wrapper/assets/130472005/ffc23081-8583-4c52-9cde-71e73ab57e45)

Launch Arguments:
ros2 launch zed_wrapper zed2i.launch.py publish_imu_tf:=False publish_urdf:=False

**Comment by anath93** [comment]
@Myzhar So when I do publish_imu_tf: false, it does work but when I publish_tf to false as my odometry tf is coming from different source, it does not work. 
![image](https://github.com/stereolabs/zed-ros2-wrapper/assets/130472005/b3506c24-1376-40a2-84f7-7d90230309d6)

**Comment by Myzhar** [comment]
Sorry, this is not clear. Can you explain better what you are doing?
What launch file are you using?
What parameters are you using?

**Comment by anath93** [comment]
Yes when I launch the zed_wrapper as below:
ros2 launch zed_wrapper zed2i.launch.py publish_tf:=False (because I do not want base link --> odom be published, the imu_tf still exists.
But as you suggested above ros2 launch zed_wrapper zed2i.launch.py publish_imu_tf:=False, then imu_tf does not get broadcasted.

**Comment by anath93** [comment]
@Myzhar, did you had a chance to look at this ?

**Comment by Myzhar** [comment]
@anath93 yes, I could replicate this. It's a wrong behavior: when `publish_tf` is set to `False` the related `publish_map_tf` and `publish_imu_tf` are not processed and they use the default value that is `true`.
I'm going to fix this wrong behavior and merge the fix before the end of the day

**Comment by anath93** [comment]
@Myzhar Thank you, please let me know once its pushed !

**Comment by Myzhar** [comment]
@anath93 can you test the fix?

**Comment by anath93** [comment]
> @anath93 can you test the fix?

ros2 launch zed_wrapper zed2i.launch.py publish_tf:=False
So now the odom and map frames are not getting published, which is good but still the zed2i_imu_link gets published, even if add argument of publish_imu_tf to false but same result.

**Comment by Myzhar** [comment]
Be aware that you must wait for the TF to time out when it's first published.
You can use `rqt` and the `Runtime Monitor` plugin to be sure that TF are enabled/disabled

Disabled:
![image](https://github.com/stereolabs/zed-ros2-wrapper/assets/3648617/c084ead4-ee0c-4876-bf40-15f5a68de2d7)

IMU Enabled:
![image](https://github.com/stereolabs/zed-ros2-wrapper/assets/3648617/66d99694-1e95-401f-8015-4b78e20076cf)

All Enabled:
![image](https://github.com/stereolabs/zed-ros2-wrapper/assets/3648617/38e4066f-8d54-43e8-99a1-447eacb998e8)

**Comment by Myzhar** [comment]
This command disables the broadcasting of all the TFs:
`$ ros2 launch zed_wrapper zed2i.launch.py publish_tf:=False publish_imu_tf:=False`

**Comment by anath93** [comment]
> This command disables the broadcasting of all the TFs: `$ ros2 launch zed_wrapper zed2i.launch.py publish_tf:=False publish_imu_tf:=False`

Yes this one worked ! Thank you. 

One last question:
Should'nt this should be set to 0's when publish_tf is set to False ?
![image](https://github.com/stereolabs/zed-ros2-wrapper/assets/130472005/6a3bf747-a4f0-480d-ad54-52dc272a745a)

**Comment by Myzhar** [comment]
The TF broadcasting is disabled, but the Wrapper internally performs the processing for Positional Tracking to publish `odom` and `pose` related topics. You can turn off the module if you want, but the SDK requires Positional Tracking also for other type of processings (e.g. Depth Stabilization).

**Comment by anath93** [comment]
Got it, that makes sense. Thank you again. I am going to close this topic !

**Comment by anath93** [comment]
@Myzhar I think there could be another potential issue, when the depth_mode is turned off, the IMU frame still gets published.

**Comment by Myzhar** [comment]
That's correct. Depth and IMU are not related, so you must explicitly disable it if you do not need it.

**Comment by anath93** [comment]
@Myzhar I manually added to components file and it worked, all the desired topics are up. But if you feel this could cause any unknown error in future, please let me know. 

  if (!mPublishImuTF || mDepthMode == sl::DEPTH_MODE::NONE) {
    return;
  }

**Comment by Myzhar** [comment]
The problem is really related to the fact that when Depth is disabled the Positional Tracking is automatically disabled and the parameters are not processed, so `mPublishImuTF` keeps the default values that is `true`.
The fix is to move the parameter `publish_imu_tf` from `pos_tracking` to `sensors` because it's more correct.

**Comment by anath93** [comment]
I agree with you on that !

**Comment by Myzhar** [comment]
I thank you for catching this issue, it's really important to fix all the possible configurations of the node.
I'm going to fix this tomorrow (evening now here in Europe), I will trigger you as soon as it's ready

**Comment by Myzhar** [comment]
@anath93 please test the new fix

**Comment by anath93** [comment]
> I thank you for catching this issue, it's really important to fix all the possible configurations of the node. I'm going to fix this tomorrow (evening now here in Europe), I will trigger you as soon as it's ready

Thank you Myzhar, everything looks good including params file which makes more sense now with segregation of sensor part. I work in USA and its nice to meet you.
