### ISSUE TITLE
Zed-x  camera

### ISSUE THREAD

**Issue by Indro-mostafa** [stereolabs/zed-ros2-wrapper#182]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Issue Description:

Upon executing the ROS2 launch command ros2 launch zed_wrapper zedx.launch.py, I receive warnings indicating that the cameras are not detected, specifically:

less

[WARN] [1694091471.724654966] [zed1.zed_node]: Error opening camera: CAMERA NOT DETECTED
[zed_wrapper-4] [WARN] [1694091471.721022979] [zed2.zed_node]: Error opening camera: CAMERA NOT DETECTED

As a temporary remedy, rebooting the system sometimes allows the cameras to function properly. However, upon stopping the camera nodes and restarting them, the error reappears. Consequently, another system reboot is often required to potentially resolve the problem. This workaround is inconsistent as, in certain instances, even after rebooting, neither of the cameras are detected and operational.

### Steps to Reproduce

1.Execute Launch Command:ros2 launch zed_wrapper zedx.launch.py
2.i will get the error [[WARN] [1694091471.724654966] [zed1.zed_node]: Error opening camera: CAMERA NOT DETECTED
[zed_wrapper-4] [WARN] [1694091471.721022979] [zed2.zed_node]: Error opening camera: CAMERA NOT DETECTED

3.Reboot the system the error will be gone when  relaunch the command  the two  cameras will be back
4.stop the launch and relaunch a gain 
5. i get the same error 
6. reboot and restart the service 
7. launch again one of the cameras will be working and the other one will be working 
8. reboot and restart the service  
9. the camera that wasn't working will work and the other one will not be working 
10. reboot and restart the service  
11. both cameras wont be working 

...

### Expected Result

Both cameras should be working when lunching them 

### Actual Result

Sometime they will work in first lunch after restarting the system then they will not work in second lunch 

### ZED Camera model

ZED

### Environment

```shell
OS: Ubuntu 20.04  
CPU: Arm
GPU: Zed box Orin  
Zed SDK version: v35.3
ROs2
```

**Comment by Myzhar** [comment]
Hi @Indro-mostafa 
please write an email to support@stereolabs.com 
This is not a wrapper issue.
