### ISSUE TITLE
gstreamer for external processing

### ISSUE THREAD

**Issue by stevenPennock** [stereolabs/zed-ros2-wrapper#183]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

I would like to connect a ZED 2i to a raspberry pi or Jetson Nano (running ROS2 humble and on a mobile manipulator) and then let a server (also running ROS2 humble) on the same network do the heavy lifting with an Nvidia GPU. I saw the gstreaming RTSP but I couldn't find a way to use that in combination with ROS2. Is it possible that this could be implemented into the zed-ros2-wrapper?Raspberry Pi

**Comment by Myzhar** [comment]
Hi @stevenPennock 
this is not possible. The ZED SDK does not accept GStreamer streams as input.
The ROS 2 Wrapper only accepts the same camera input modes available with the ZED SDK:
Live camera, SVO, and ZED Local Stream (oncoming).
