### ISSUE TITLE
Fix common.yaml config

### ISSUE THREAD

**Issue by umnrobotics** [stereolabs/zed-ros2-wrapper#185]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

On commit df92cb6 the debug_video_depth was set to true in the default config. 

### Steps to Reproduce

https://github.com/stereolabs/zed-ros2-wrapper/blob/master/zed_wrapper/config/common.yaml#L172

### Expected Result

It should be set to false

### Actual Result

This should be set to false by default

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubuntu 22.04
CPU: x86_64
```

**Comment by Myzhar** [comment]
Fixed by #186
