### ISSUE TITLE
Dashing Support

### ISSUE THREAD

**Issue by clungzta** [stereolabs/zed-ros2-wrapper#2]
Hi,

I see that this package supports Crystal at this stage.

I did make an attempt at building it on my Dashing system. I successfully got through  most of the build steps, until:
`colcon build --symlink-install --packages-select stereolabs_zed --cmake-args=-DCMAKE_BUILD_TYPE=Release`

Where the following issue occurred:
```
Starting >>> stereolabs_zed
--- stderr: stereolabs_zed                         
CMake Error at CMakeLists.txt:155 (rclcpp_components_register_nodes):
  Unknown CMake command "rclcpp_components_register_nodes".


---
Failed   <<< stereolabs_zed	[ Exited with code 1 ]
```

Is Dashing support planned?

Best Regards

**Comment by Myzhar** [comment]
Hi @clungzta 
Porting the ZED node to Dashing requires a lot of work since it introduced a lot of novelties. 
We are working on it and it will be ready soon.

**Comment by clungzta** [comment]
Hi

Thank you for the status update and active development.
I look forward to using it upon release.

Best Regards

**Comment by estefaniatc** [comment]
Hi,

Is there any update on the expected support for Dashing?

**Comment by EunSungYang** [comment]
@Myzhar 
Hi.

I have a same issue.
Can you tell me when the problem will be solved?

**Comment by mhaboali** [comment]
Any updates on the Dashing release?

Thanks!

**Comment by cardboardcode** [comment]
@Myzhar Thank you for the ROS2 wrapper of Zed Camera.

Same question as the rest. Any updates on the Dashing or later releases?

**Comment by Myzhar** [comment]
We are going to work to release an update for the new ROS2 LTS (Foxy) that will be released in May:
https://index.ros.org/doc/ros2/Releases/Release-Foxy-Fitzroy/

**Comment by james-yoo** [comment]
@Myzhar SDK update for the ROS2 Foxy will be compatible Dashing as well?

**Comment by Myzhar** [comment]
@james-yoo I must verify what's different between the two versions

**Comment by mehmetkillioglu** [comment]
> We are going to work to release an update for the new ROS2 LTS (Foxy) that will be released in May:
> https://index.ros.org/doc/ros2/Releases/Release-Foxy-Fitzroy/

Hi,

Any updates for Foxy release? 

Best,
Mehmet

**Comment by Myzhar** [comment]
Work in progress 
Lot of changes and many quality checks to do.
It will take yet a bit of time before the final release

**Comment by annb3** [comment]
Hi, 
Any updates for Dashing release?

Best regards,
Anna

**Comment by Myzhar** [comment]
No Dashing release, Eloquent release is instead almost ready:
https://github.com/stereolabs/zed-ros2-wrapper/tree/eloquent

**Comment by mehmetkillioglu** [comment]
> Hi,
> Any updates for Dashing release?
> 
> Best regards,
> Anna

Hi,

From this [repository](https://github.com/mehmetkillioglu/zed-ros2-wrapper), you can find my custom made version of zed wrapper for Dashing. The tests were not done thoroughly, and I cannot claim it will work fine as I am not affiliated with Stereolabs. I do not accept any liability. Might not be suitable for production-level applications.

Although if you use and find some problems with it, you can create an issue on my repository though. I can try to fix it.

Best,
Mehmet

**Comment by Myzhar** [comment]
FYI the `eloquent` version of the ZED ROS2 wrapper will not be based on LifeCycle anymore, but it will be based on the "straight" `Node` model.
This is because the LifeCycle model is not yet totally supported by ROS2 and many packages and nodes like Image Transport and TF do not handle it yet correctly.

**Comment by Myzhar** [comment]
Eloquent version has been released

**Comment by Rayman** [comment]
@Myzhar can you elaborate a little more about the issues you encountered with LifeCycle? What exactly is not supported? I'm just getting into ROS2 and I thought LifeCycle was a big improvement.

**Comment by Myzhar** [comment]
Hi @Rayman 
Lifecycle is really interesting, but the many important features for us were not available, mainly `image_transport` and `TF broadcasting`, but there were problems also with other features.
As far as I know `image_transport` is not yet available with Lifecycle nodes even with ROS2 Foxy

**Comment by Rayman** [comment]
@Myzhar thank you!

Strange that this is still not supported. I'm linking the issue here for future reference:
https://github.com/ros-perception/image_common/issues/108
https://github.com/ros-perception/image_common/pull/167
