### ISSUE TITLE
Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY)

### ISSUE THREAD

**Issue by harisiva1** [stereolabs/zed-ros2-wrapper#20]
Hello,
I am using ROS2 ELOQUENT and i am trying to build zed-ros2-wrapper and i get the below error.attached the image.
I have tried with both master branch and eloquent branch but i get the same error.
Please support!

    OS: Ubuntu
    OS 18.04
    ZED SDK Version: 3.2
    ROS Wrapper version: eloquent

![Screenshot from 2020-11-22 19-44-57](https://user-images.githubusercontent.com/68550704/99914317-e167f780-2cfc-11eb-8985-a52db9fc2968.png)

**Comment by harisiva1** [comment]
Hi,
i have tried few things so far but still get the same error.

first try:https://github.com/torch/torch7/issues/1138
 secondly i tried to install cuda10.2 once again but the local(run) file throws a error saying that install of driver component failed like here. https://forums.developer.nvidia.com/t/error-while-install-cuda-toolkit-10-2-on-ubuntu-18-04-3/109829/3
i could able to install only deb(local)
do you have some suggestions to overcome this error??
i have also tried to run zed package in ros melodic still ended up with this cuda error
![Screenshot from 2020-11-23 11-18-34](https://user-images.githubusercontent.com/68550704/99951017-b5d92180-2d7d-11eb-8917-fd4698eeb5cb.png)

**Comment by Myzhar** [comment]
Hi @harisiva1 
can you post the output of the command `nvcc -V`?

**Comment by harisiva1** [comment]
![Screenshot from 2020-11-23 11-32-19](https://user-images.githubusercontent.com/68550704/99952220-96db8f00-2d7f-11eb-81f3-bc8230c67390.png)

**Comment by Myzhar** [comment]
@harisiva1 as you can see this is your problem.
Your system sees CUDA 9.1 as default, not CUDA 10.2.
I suggest you clean up your system purging CUDA and installing again CUDA 10.2.
Here you can find a bunch of valid methods to perform this task:
https://askubuntu.com/questions/530043/removing-nvidia-cuda-toolkit-and-installing-new-one

**Comment by harisiva1** [comment]
![Screenshot from 2020-11-23 12-17-09](https://user-images.githubusercontent.com/68550704/99956159-d907cf00-2d85-11eb-9d63-c8594dd9e64b.png)
but i also see cuda version 11 when i run nvidia-smi command

**Comment by Myzhar** [comment]
So your system is definitively in a chaotic configuration.
At this point, I suggest you remove also the Nvidia driver and install everything from scratch.

**Comment by harisiva1** [comment]
you can consider this issue as closed.
with the current configuration i have been able to run ZED launch file in both ros melodic and eloquent and perform spatial mapping.Nevertheless i will try to do as per your suggestion.
thanks!
