### ISSUE TITLE
Issues with Running zed_display_rviz2 on Jetson Orin with Docker Container

### ISSUE THREAD

**Issue by dsiwela** [stereolabs/zed-ros2-wrapper#202]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hello,

I am currently working on setting up the ZED ROS2 wrapper using the `Dockerfile.l4t35_1-humble-release` on my Jetson Orin. I have made a modification to the Dockerfile to change the base image from a ROS2 base image to a desktop image ('dustynv/ros:humble-desktop-l4t-r35.1.0') as I couldnt get rviz2 to work otherwise. 

The build process for the ZED SDK, ROS2, and zed-ros2-wrapper completes successfully. I am also able to launch `rviz2`, but I encounter issues when trying to run `zed_display_rviz2`. Specifically, I receive the error message "Package 'zed_display_rviz2' not found" and "zed_display_rviz2: No definition of [grid_map_rviz_plugin] for OS version [focal]".

### Steps to Reproduce

1. docker build -t "<image_tag>" -f Dockerfile.l4t35_1-humble-release .
2. sudo docker run -it --gpus all --runtime nvidia --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev -e NVIDIA_DRIVER_CAPABILITIES=all 2aedc5a85913 /bin/bash
3. ros2 launch zed_display_rviz2 display_zed_cam.launch.py camera_model:='zed2i'

### Expected Result

To of visualised cameras data on rviz2

### Actual Result

user@ubuntu:~/zed-ros2-wrapper/docker$ sudo docker run -it --gpus all --runtime nvidia --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev -e NVIDIA_DRIVER_CAPABILITIES=all 2aedc5a85913 /bin/bash
ZED ROS2 Docker Image
---------------------
ROS distro:  humble
DDS middleware:  rmw_cyclonedds_cpp
---
Available ZED packages:
zed_components
zed_interfaces
zed_ros2
zed_wrapper
---------------------
root@8c6afed509d5:~/ros2_ws# ros2 launch zed_wrapper zed_camera.launch.py camera_model:='zed2i' 
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-01-15-09-30-04-268385-8c6afed509d5-71
[INFO] [launch]: Default logging verbosity is set to INFO
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: .
[INFO] [robot_state_publisher-1]: process started with pid [74]
[INFO] [zed_wrapper-2]: process started with pid [76]
[zed_wrapper-2] /root/ros2_ws/install/zed_wrapper/lib/zed_wrapper/zed_wrapper: error while loading shared libraries: libnvbuf_utils.so.1.0.0: cannot open shared object file: No such file or directory
[ERROR] [zed_wrapper-2]: process has died [pid 76, exit code 127, cmd '/root/ros2_ws/install/zed_wrapper/lib/zed_wrapper/zed_wrapper --ros-args -r __node:=zed_node -r __ns:=/zed --params-file /root/ros2_ws/install/zed_wrapper/share/zed_wrapper/config/common.yaml --params-file /root/ros2_ws/install/zed_wrapper/share/zed_wrapper/config/zed2i.yaml --params-file /tmp/launch_params_i9qzhjb_'].
[robot_state_publisher-1] Link zed_camera_center had 2 children
[robot_state_publisher-1] Link zed_left_camera_frame had 1 children
[robot_state_publisher-1] Link zed_left_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed_right_camera_frame had 1 children
[robot_state_publisher-1] Link zed_right_camera_optical_frame had 0 children
[robot_state_publisher-1] [INFO] [1705307405.246085801] [zed.zed_state_publisher]: got segment zed_camera_center
[robot_state_publisher-1] [INFO] [1705307405.246274733] [zed.zed_state_publisher]: got segment zed_camera_link
[robot_state_publisher-1] [INFO] [1705307405.246300205] [zed.zed_state_publisher]: got segment zed_left_camera_frame
[robot_state_publisher-1] [INFO] [1705307405.246313933] [zed.zed_state_publisher]: got segment zed_left_camera_optical_frame
[robot_state_publisher-1] [INFO] [1705307405.246325262] [zed.zed_state_publisher]: got segment zed_right_camera_frame
[robot_state_publisher-1] [INFO] [1705307405.246335726] [zed.zed_state_publisher]: got segment zed_right_camera_optical_frame

### ZED Camera model

ZED2i

### Environment

```shell
- Jetson Orin
- Docker base image: dustynv/ros:humble-desktop-l4t-r35.1.0
- ZED SDK Version: 4.07
- ROS2 Version: Humble Hawksbill
```

**Comment by Myzhar** [comment]
@dsiwela `zed_display_rviz2` is not part of this repository. 
You must install the repository [zed-ros2-examples](https://github.com/stereolabs/zed-ros2-examples) as describes in the README
