### ISSUE TITLE
[Question] Difference in depth image quality between SDK 3.3.0 and SDK 3.4.0

### ISSUE THREAD

**Issue by laszloturanyi** [stereolabs/zed-ros2-wrapper#24]
Hi,

We experienced some difference when using ZED SDK 3.4.0 compared to version 3.3.0 regarding the depth image quality.

See attached attached images below.
The depth quality with SDK 3.3.0 seems to be better. We used zed-ros2-wrapper with same configuration on the same svo recording. The compute platform is a Jetson AGX Xavier.

**RGB image**
![00009](https://user-images.githubusercontent.com/58770032/107971559-eb735c80-6fb2-11eb-8b69-cc72de0dfbe8.jpg)

**SDK 3.3.0**
![00009_depth](https://user-images.githubusercontent.com/58770032/107971321-a0594980-6fb2-11eb-9d37-b455026f2b5a.png)

**SDK 3.4.0**
![00009_depth](https://user-images.githubusercontent.com/58770032/107971356-a7805780-6fb2-11eb-8f9f-74b8b0018600.png)

Can you tell us what could be the cause for this? We chose to revert to SDK 3.3.0.
Thanks!

**Comment by Myzhar** [comment]
Hi @laszloturanyi 
Thank you for reporting. 
This seems to be a problem related to the ZED SDK. Can you please send an email to support@stereolabs.com describing it in details? Is it present also on desktop platforms and using different depth qualities?

**Comment by laszloturanyi** [comment]
Hi @Myzhar, 

Thank you for your answers. I have sent an email to the address. We also tried this on a pc with ubuntu 18.04 and we could see the same issue. Depth quality was set to performance (1) and did not try it with any other setting.

Regards,
Laszlo

**Comment by Myzhar** [comment]
Hi @laszloturanyi 
we identified the issue in the ZED SDK and we are solving it.
It will be fixed with the next patch release.

Thank you for reporting

**Comment by laszloturanyi** [comment]
Wow. What a quick reaction.
Thank you for your help.
