### ISSUE TITLE
I meet this issue: can not find this two packages [point_cloud_transport] [zstd_point_cloud_transport]

### ISSUE THREAD

**Issue by like2000522** [stereolabs/zed-ros2-wrapper#253]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
zed_components: Cannot locate rosdep definition for [point_cloud_transport]
zed_wrapper: Cannot locate rosdep definition for [zstd_point_cloud_transport]
Continuing to install resolvable dependencies...
[zstd_point_cloud_transport]

### Steps to Reproduce

1.1
2.
3.11
...
1

### Expected Result

1

### Actual Result

1

### ZED Camera model

ZED

### Environment

```shell
ubuntu20.04
```

**Comment by Myzhar** [comment]
Hi @like2000522 
if you are using `Foxy`, then you can ignore this message.
They are both not available on Foxy and the build process will ignore their usage.
