### ISSUE TITLE
jetson zed build failed

### ISSUE THREAD

**Issue by seongjin-lim** [stereolabs/zed-ros2-wrapper#272]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.

### Description

Starting >>> zed_components
--- stderr: zed_components                               
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp: In member function ‘void stereolabs::ZedCamera::getOdParams()’:
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:1656:51: error: ‘CUSTOM_YOLOLIKE_BOX_OBJECTS’ is not a member of ‘sl::OBJECT_DETECTION_MODEL’; did you mean ‘CUSTOM_BOX_OBJECTS’?
 1656 |   if (mObjDetModel == sl::OBJECT_DETECTION_MODEL::CUSTOM_YOLOLIKE_BOX_OBJECTS) {
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   CUSTOM_BOX_OBJECTS
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:1698:51: error: ‘CUSTOM_YOLOLIKE_BOX_OBJECTS’ is not a member of ‘sl::OBJECT_DETECTION_MODEL’; did you mean ‘CUSTOM_BOX_OBJECTS’?
 1698 |   if (mObjDetModel != sl::OBJECT_DETECTION_MODEL::CUSTOM_YOLOLIKE_BOX_OBJECTS) {
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   CUSTOM_BOX_OBJECTS
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp: In member function ‘bool stereolabs::ZedCamera::startObjDetect()’:
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:5188:51: error: ‘CUSTOM_YOLOLIKE_BOX_OBJECTS’ is not a member of ‘sl::OBJECT_DETECTION_MODEL’; did you mean ‘CUSTOM_BOX_OBJECTS’?
 5188 |   if (mObjDetModel == sl::OBJECT_DETECTION_MODEL::CUSTOM_YOLOLIKE_BOX_OBJECTS) {
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   CUSTOM_BOX_OBJECTS
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:5190:10: error: ‘struct sl::ObjectDetectionParameters’ has no member named ‘custom_onnx_file’
 5190 |     od_p.custom_onnx_file = sl::String(mYoloOnnxPath.c_str());
      |          ^~~~~~~~~~~~~~~~
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:5191:10: error: ‘struct sl::ObjectDetectionParameters’ has no member named ‘custom_onnx_dynamic_input_shape’
 5191 |     od_p.custom_onnx_dynamic_input_shape = sl::Resolution(mYoloOnnxSize, mYoloOnnxSize);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp: In member function ‘void stereolabs::ZedCamera::processDetectedObjects(rclcpp::Time)’:
/workspaces/isaac_ros-dev/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:8343:53: error: ‘CUSTOM_YOLOLIKE_BOX_OBJECTS’ is not a member of ‘sl::OBJECT_DETECTION_MODEL’; did you mean ‘CUSTOM_BOX_OBJECTS’?
 8343 |     if (mObjDetModel != sl::OBJECT_DETECTION_MODEL::CUSTOM_YOLOLIKE_BOX_OBJECTS) {
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     CUSTOM_BOX_OBJECTS
gmake[2]: *** [CMakeFiles/zed_camera_component.dir/build.make:118: CMakeFiles/zed_camera_component.dir/src/zed_camera/src/zed_camera_component.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/zed_camera_component.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< zed_components [25.5s, exited with code 2]

Summary: 1 package finished [29.5s]
  1 package failed: zed_components
  2 packages had stderr output: zed_components zed_interfaces
  1 package not processed

### ZED Camera model

ZED

### Environment

```shell
jetson orin

zed wrapper docker build
```
If you build zed using what is in cumotion, the above error occurs.
https://nvidia-isaac-ros.github.io/getting_started/hardware_setup/sensors/zed_setup.html

**Comment by Myzhar** [comment]
You need to install the latest ZED SDK for the latest version of the `master` branch.
