### ISSUE TITLE
Error sl/CameraOne.hpp: No such file or directory - Jetson docker container

### ISSUE THREAD

**Issue by creix** [stereolabs/zed-ros2-wrapper#280]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hello, I have encountered the following problem when running the script `./jetson_build_dockerfile_from_sdk_and_l4T_version.sh`:

```
In file included from /root/ros2_ws/src/zed_components/src/zed_camera/src/zed_camera_one_component.cpp:15:
/root/ros2_ws/src/zed_components/src/zed_camera/include/zed_camera_one_component.hpp:19:10: fatal error: sl/CameraOne.hpp: No such file or directory
   19 | #include <sl/CameraOne.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Steps to Reproduce

1. git clone  --recursive https://github.com/stereolabs/zed-ros2-wrapper.git
2. ./jetson_build_dockerfile_from_sdk_and_l4T_version.sh l4t-r35.4.1 zedsdk4.1.2

### Expected Result

The compilation should be completed without any error

### Actual Result

The error is the following:

```
In file included from /root/ros2_ws/src/zed_components/src/zed_camera/src/zed_camera_one_component.cpp:15:
/root/ros2_ws/src/zed_components/src/zed_camera/include/zed_camera_one_component.hpp:19:10: fatal error: sl/CameraOne.hpp: No such file or directory
   19 | #include <sl/CameraOne.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubuntu 20.04.6 LTS
GPU: Nvidia Jetson Xavier
```

**Comment by Myzhar** [comment]
Zed SDK V4.2.2 is required

**Comment by creix** [comment]
> Zed SDK V4.2.2 is required

Thank you, error resolved.
Could be useful to update the readme of the example with the last version of the SDK.
