### ISSUE TITLE
RCLCPP_DEBUG_STREAM and so on Compilation error

### ISSUE THREAD

**Issue by ZJF-BOY** [stereolabs/zed-ros2-wrapper#30]
**Describe the bug**

**Device information:**
 - OS: Ubuntu
 - OS version:  18.04
 - CPU: [e.g. i7, Jeston Nano, Jetson TX2]
 - GPU Nvidia:  [e.g. GTX1080, RTX1070]
 - ZED SDK Version: [e.g. v3.1.2, v2.8.5]
 - ROS Wrapper version: [e.g. v2.8.5, latest master]

**Screenshots**
/home/nvidia/ZED2/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:1970:63: error: invalid operands of types ‘const char [21]’ and int’ to binary ‘operator<<’
     RCLCPP_DEBUG_STREAM( get_logger(), "Camera Frame size : " << mCamWidth << "x" << mCamHeight);
                                        ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/nvidia/ZED2/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:1970:5: error: ‘RCLCPP_DEBUG_STREAM’ was not declared in this scope
     RCLCPP_DEBUG_STREAM( get_logger(), "Camera Frame size : " << mCamWidth << "x" << mCamHeight);
     ^~~~~~~~~~~~~~~~~~~
/home/nvidia/ZED2/src/zed-ros2-wrapper/zed_components/src/zed_camera/src/zed_camera_component.cpp:1970:5: note: suggested alternative: ‘RCLCPP_DEBUG_ONCE’
     RCLCPP_DEBUG_STREAM( get_logger(), "Camera Frame size : " << mCamWidth << "x" << mCamHeight);
     ^~~~~~~~~~~~~~~~~~~
     RCLCPP_DEBUG_ONCE
make[2]: *** [CMakeFiles/zed_camera_component.dir/src/zed_camera/src/zed_camera_component.cpp.o] Error 1
make[1]: *** [CMakeFiles/zed_camera_component.dir/all] Error 2
make: *** [all] Error 2

**Additional context**
I am using ROS2-dashing， which compile  error

**Comment by Myzhar** [comment]
Hi @ZJF-BOY 
the `RCLCPP_DEBUG_STREAM` macro has been added to ROS2 starting from the `eloquent elusor` release.
The ZED ROS2 Wrapper has been written for ROS2 Eloquent (you can read it in the ["Prerequisites" in the README](https://github.com/stereolabs/zed-ros2-wrapper#prerequisites)) and it is not backward compatible with ROS2 Dashing because of the many differences between the two releases.

**Comment by ZJF-BOY** [comment]
thanks
