### ISSUE TITLE
Is it possible to use the terminal to specify the resolution to pass parameters？

### ISSUE THREAD

**Issue by ZJF-BOY** [stereolabs/zed-ros2-wrapper#38]
Hello，I have a problem with my recent project. I hope to set the resolution when I start the zed_wrapper.
Can  I use this format: ros2 launch zed_wrapper zed2.launch.py --ros-args -p resolution:=2 ? Hope for your help

**Comment by ZJF-BOY** [comment]
solved

**Comment by Myzhar** [comment]
@ZJF-BOY can you post the solution that you used?
It can be useful for other users that will land on this issue.
