### ISSUE TITLE
[Question] Can I change FOV of Zed2?

### ISSUE THREAD

**Issue by luan1412167** [stereolabs/zed-ros2-wrapper#47]
Hi team,
I am studying Zed2 camera. I want to record left + right camera with FHD resulotion and maximize FOV?
Can I change FOV of Zed2? Was it configure in calibration process? Should I change it?
Thank team

**Comment by obraun-sl** [comment]
Hi,
You can't change the FoV of the camera (it's a fixed focal length). You can only change the resolution of the camera that will impact the FoV of the camera : 
HD720 and HD2K will give the maximum fov compared to HD1080.

**Comment by luan1412167** [comment]
Many thanks for your support. Keep it up.
