### ISSUE TITLE
[Feature] I saw a support of ZED 2i on Foxy, Could you make it available for Eloquent as well?

### ISSUE THREAD

**Issue by CircleOnCircles** [stereolabs/zed-ros2-wrapper#52]
I saw a support of ZED 2i on Foxy, Could you make it available for Eloquent as well?

**Comment by Myzhar** [comment]
The [Eloquent branch](https://github.com/stereolabs/zed-ros2-wrapper/tree/eloquent) should support the ZED2i. Are you facing issues with it?

**Comment by CircleOnCircles** [comment]
I could not find the launch file on the branch.

**Comment by CircleOnCircles** [comment]
i moved to foxy.
