### ISSUE TITLE
[BUG] No module named 'em'

### ISSUE THREAD

**Issue by an99990** [stereolabs/zed-ros2-wrapper#53]
**Describe the bug**
I tried to build the repo and got No module named 'em'

**Device information:**
 - OS: Ubuntu
 - OS version: 20.04
 - ZED SDK Version: 3.5
 - ROS Wrapper version: latest master

**To Reproduce**
installation instructions given in repo
i then install emy via pip but i still get the error
**Screenshots**
![image](https://user-images.githubusercontent.com/87030365/131868880-5cc6d63d-1e04-45f7-983a-a2f85b744d42.png)

**Comment by Myzhar** [comment]
Have you tried with 
`$ sudo apt-get install python3-empy`
see https://answers.ros.org/question/257757/importerror-no-module-named-em-error/

**Comment by Myzhar** [comment]
Be sure to be using Python3:
https://answers.ros.org/question/337135/catkin_make-no-module-named-catkin_pkg/

**Comment by an99990** [comment]
yes thank you, i have managed to install the packages and this is the error that does not involve any module
![image](https://user-images.githubusercontent.com/87030365/131872233-aa67093f-9a35-47c9-bd5a-1976ed58744c.png)

please help, thanks

**Comment by an99990** [comment]
bot sure what happend but i changed the python version and now im good.
Thank you again @Myzhar
