### ISSUE TITLE
ZED2i Support ROS2 Eloquent 18.04

### ISSUE THREAD

**Issue by hwhite-eng** [stereolabs/zed-ros2-wrapper#57]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Please provide support for your new ZED2i camera in your ROS2 wrapper for the NVIDIA Jetson community.
Thanks

**Comment by Myzhar** [comment]
Eloquent is EOL. This Feature request is no more actual.
