### ISSUE TITLE
Unable to build zed_components

### ISSUE THREAD

**Issue by Nykri** [stereolabs/zed-ros2-wrapper#58]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Colcon fails to build the ROS2 wrapper. The problems seems to be zed_components.

### Steps to Reproduce

```
cd ~/ros2_ws/src/ #use your current ros2 workspace folder
git clone https://github.com/stereolabs/zed-ros2-wrapper.git
cd ..
rosdep install --from-paths src --ignore-src -r -y
colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release
```

### Expected Result

All packages are built

### Actual Result

1 package failed: zed_components
  1 package had stderr output: zed_components

The whole output is in the following file :
[colcon_output.txt](https://github.com/stereolabs/zed-ros2-wrapper/files/7416910/colcon_output.txt)

### ZED Camera model

ZED2

### Environment

```shell
OS: Ubuntu focal 20.04
CPU: x86_64
GPU: Nvidia 2060
ZED SDK: Tried with 3.5 and 3.6
ROS: Foxy
CUDA: 11.4
```

**Comment by Myzhar** [comment]
@Nykri have you found a solution to your problem?

**Comment by Nykri** [comment]
No, not really, I moved to something else.

**Comment by swiz23** [comment]
You have to do 

git clone --recursive https://github.com/stereolabs/zed-ros2-wrapper.git

as the zed-ros2-interfaces directory is a git submodule

**Comment by Myzhar** [comment]
@swiz23 this is an old issue. The repository was not yet splitter when @Nykri faced problems while compiling

**Comment by Genozen** [comment]
Sorry, I have similar error. Any chance this was resolved?
```
@genozen:~/Desktop/ros2_ws/src$ colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release
[0.920s] WARNING:colcon.colcon_core.package_selection:Some selected packages are already built in one or more underlay workspaces:
	'image_transport' is in: /opt/ros/foxy
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding image_transport

This may be promoted to an error in a future release of colcon-override-check.
Starting >>> image_transport
Starting >>> zed_interfaces
Starting >>> camera_calibration_parsers                                           
Finished <<< camera_calibration_parsers [1.09s]                          
Starting >>> camera_info_manager
Finished <<< image_transport [1.58s]                                     
Finished <<< camera_info_manager [0.57s]                                
Starting >>> image_common
Finished <<< zed_interfaces [2.18s]                                  
Starting >>> zed_components                        
Finished <<< image_common [0.49s]
--- stderr: zed_components                         
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindZED.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ZED", but
  CMake did not find one.

  Could not find a package configuration file provided by "ZED" (requested
  version 3) with any of the following names:

    ZEDConfig.cmake
    zed-config.cmake

  Add the installation prefix of "ZED" to CMAKE_PREFIX_PATH or set "ZED_DIR"
  to a directory containing one of the above files.  If "ZED" provides a
  separate development package or SDK, be sure it has been installed.


---
Failed   <<< zed_components [0.13s, exited with code 1]

Summary: 5 packages finished [2.92s]
  1 package failed: zed_components
  1 package had stderr output: zed_components
  2 packages not processed

```

**Comment by Myzhar** [comment]
@Genozen this is a closed issue. Always open a new issue and eventually cite yhe closed one if you face a similar problem.

However, the problem is different and the error is self-expaining: the compiler cannot find the ZED SDK. Did you install it?

**Comment by sandipsharan** [comment]
Hey @Myzhar I am facing the same problem I have installed ZED SDK in the computer and confirmed it with doing ls /usr/local/zed and I can see the zed-config.cmake file in there but even after setting the ZED_DIR to that path I am experiencing the same issue in here. Can you help me with this?

**Comment by Myzhar** [comment]
@sandipsharan  this is a closed issue. Always open a new issue and eventually cite the closed one if you face a similar problem.
