### ISSUE TITLE
frame does not exist

### ISSUE THREAD

**Issue by an99990** [stereolabs/zed-ros2-wrapper#64]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I didnt change anything from the repo since i started using it. I just discovered an issue recently.

### Steps to Reproduce

`ros2 launch zed_display_rviz2 display_zed2.launch.py`

### Expected Result

no errors

### Actual Result

[INFO] [launch]: All log files can be found below /home/tres/.ros/log/2021-11-15-12-19-05-535142-halodi-Precision-5550-36572
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [36575]
[INFO] [zed_wrapper-2]: process started with pid [36577]
[INFO] [rviz2-3]: process started with pid [36579]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link zed2_camera_center had 4 children
[robot_state_publisher-1] Link zed2_baro_link had 0 children
[robot_state_publisher-1] Link zed2_left_camera_frame had 2 children
[robot_state_publisher-1] Link zed2_left_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed2_temp_left_link had 0 children
[robot_state_publisher-1] Link zed2_mag_link had 0 children
[robot_state_publisher-1] Link zed2_right_camera_frame had 2 children
[robot_state_publisher-1] Link zed2_right_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed2_temp_right_link had 0 children
[robot_state_publisher-1] 1636996745.695192530 [zed2.zed_state_publisher] [INFO] got segment base_link
[robot_state_publisher-1] 1636996745.695252072 [zed2.zed_state_publisher] [INFO] got segment zed2_baro_link
[robot_state_publisher-1] 1636996745.695260228 [zed2.zed_state_publisher] [INFO] got segment zed2_camera_center
[robot_state_publisher-1] 1636996745.695264848 [zed2.zed_state_publisher] [INFO] got segment zed2_left_camera_frame
[robot_state_publisher-1] 1636996745.695269142 [zed2.zed_state_publisher] [INFO] got segment zed2_left_camera_optical_frame
[robot_state_publisher-1] 1636996745.695273360 [zed2.zed_state_publisher] [INFO] got segment zed2_mag_link
[robot_state_publisher-1] 1636996745.695277372 [zed2.zed_state_publisher] [INFO] got segment zed2_right_camera_frame
[robot_state_publisher-1] 1636996745.695281292 [zed2.zed_state_publisher] [INFO] got segment zed2_right_camera_optical_frame
[robot_state_publisher-1] 1636996745.695285200 [zed2.zed_state_publisher] [INFO] got segment zed2_temp_left_link
[robot_state_publisher-1] 1636996745.695289091 [zed2.zed_state_publisher] [INFO] got segment zed2_temp_right_link
[zed_wrapper-2] 1636996745.701086770 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1636996745.701151587 [zed2.zed_node] [INFO]       ZED Camera Component 
[zed_wrapper-2] 1636996745.701160037 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1636996745.701165453 [zed2.zed_node] [INFO]  * namespace: /zed2
[zed_wrapper-2] 1636996745.701170642 [zed2.zed_node] [INFO]  * node name: zed_node
[zed_wrapper-2] 1636996745.701174834 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1636996745.701207525 [zed2.zed_node] [INFO] *** DEBUG parameters ***
[zed_wrapper-2] 1636996745.701218807 [zed2.zed_node] [INFO] *** GENERAL parameters ***
[zed_wrapper-2] 1636996745.701242717 [zed2.zed_node] [INFO]  * Camera model: zed2 - ZED 2
[zed_wrapper-2] 1636996745.701259867 [zed2.zed_node] [INFO]  * SDK Verbose: 1
[zed_wrapper-2] 1636996745.701274045 [zed2.zed_node] [INFO]  * SVO: 
[zed_wrapper-2] 1636996745.701286253 [zed2.zed_node] [INFO]  * SVO Loop: TRUE
[zed_wrapper-2] 1636996745.701301484 [zed2.zed_node] [INFO]  * SVO Realtime: FALSE
[zed_wrapper-2] 1636996745.701315233 [zed2.zed_node] [INFO]  * Camera name: zed2
[zed_wrapper-2] 1636996745.701331333 [zed2.zed_node] [INFO]  * Camera ID: 0
[zed_wrapper-2] 1636996745.701344472 [zed2.zed_node] [INFO]  * Camera SN: 0
[zed_wrapper-2] 1636996745.701358189 [zed2.zed_node] [INFO]  * Camera timeout [sec]: 5
[zed_wrapper-2] 1636996745.701371338 [zed2.zed_node] [INFO]  * Camera reconnection temptatives: 5
[zed_wrapper-2] 1636996745.701386504 [zed2.zed_node] [INFO]  * Camera framerate: 30
[zed_wrapper-2] 1636996745.701400022 [zed2.zed_node] [INFO]  * GPU ID: -1
[zed_wrapper-2] 1636996745.701414293 [zed2.zed_node] [INFO]  * Camera resolution: 2 - HD720
[zed_wrapper-2] 1636996745.701426834 [zed2.zed_node] [INFO]  * Camera self calibration: TRUE
[zed_wrapper-2] 1636996745.701438419 [zed2.zed_node] [INFO]  * Camera flip: FALSE
[zed_wrapper-2] 1636996745.701453428 [zed2.zed_node] [INFO]  * [DYN] Publish framerate [Hz]: 15 
[zed_wrapper-2] 1636996745.701463702 [zed2.zed_node] [INFO] *** VIDEO parameters ***
[zed_wrapper-2] 1636996745.701476542 [zed2.zed_node] [INFO]  * Use old extrinsic parameters: 0
[zed_wrapper-2] 1636996745.701489277 [zed2.zed_node] [INFO]  * [DYN] Image downsample factor: 0.5 
[zed_wrapper-2] 1636996745.701504181 [zed2.zed_node] [INFO]  * [DYN] Brightness: 4
[zed_wrapper-2] 1636996745.701517532 [zed2.zed_node] [INFO]  * [DYN] Contrast: 4
[zed_wrapper-2] 1636996745.701531857 [zed2.zed_node] [INFO]  * [DYN] Hue: 0
[zed_wrapper-2] 1636996745.701545172 [zed2.zed_node] [INFO]  * [DYN] Saturation: 4
[zed_wrapper-2] 1636996745.701558028 [zed2.zed_node] [INFO]  * [DYN] Sharpness: 4
[zed_wrapper-2] 1636996745.701570378 [zed2.zed_node] [INFO]  * [DYN] Gamma: 8
[zed_wrapper-2] 1636996745.701582759 [zed2.zed_node] [INFO]  * [DYN] Auto Exposure/Gain: TRUE
[zed_wrapper-2] 1636996745.701595314 [zed2.zed_node] [INFO]  * [DYN] Exposure: 80
[zed_wrapper-2] 1636996745.701607820 [zed2.zed_node] [INFO]  * [DYN] Gain: 80
[zed_wrapper-2] 1636996745.701621470 [zed2.zed_node] [INFO]  * [DYN] Auto White Balance: TRUE
[zed_wrapper-2] 1636996745.701634633 [zed2.zed_node] [INFO]  * [DYN] White Balance Temperature: 42
[zed_wrapper-2] 1636996745.701650101 [zed2.zed_node] [INFO]  * Video QoS History: KEEP_LAST
[zed_wrapper-2] 1636996745.701662687 [zed2.zed_node] [INFO]  * Video QoS History depth: 1

[zed_wrapper-2] 1636996692.793409811 [zed2.zed_node] [INFO]  * Video QoS History depth: 1
[zed_wrapper-2] 1636996692.793432730 [zed2.zed_node] [INFO]  * Video QoS Reliability: RELIABLE
[zed_wrapper-2] 1636996692.793454303 [zed2.zed_node] [INFO]  * Video QoS Durability: VOLATILE
[zed_wrapper-2] 1636996692.793461381 [zed2.zed_node] [INFO] *** DEPTH parameters ***
[zed_wrapper-2] 1636996692.793478991 [zed2.zed_node] [INFO]  * Depth quality: 1 - PERFORMANCE
[zed_wrapper-2] 1636996692.793496855 [zed2.zed_node] [INFO]  * Depth downsample factor: 0.5 
[zed_wrapper-2] 1636996692.793526703 [zed2.zed_node] [INFO]  * Min depth [m]: 0.2
[zed_wrapper-2] 1636996692.793543201 [zed2.zed_node] [INFO]  * Max depth [m]: 20
[zed_wrapper-2] 1636996692.793567516 [zed2.zed_node] [INFO]  * Depth Sensing Mode: 0 - STANDARD
[zed_wrapper-2] 1636996692.793588315 [zed2.zed_node] [INFO]  * Depth Stabilization: TRUE
[zed_wrapper-2] 1636996692.793609548 [zed2.zed_node] [INFO]  * OpenNI mode (16bit point cloud): FALSE
[zed_wrapper-2] 1636996692.793635852 [zed2.zed_node] [INFO]  * [DYN] Point cloud rate [Hz]: 10
[zed_wrapper-2] 1636996692.793656820 [zed2.zed_node] [INFO]  * [DYN] Depth Confidence: 50
[zed_wrapper-2] 1636996692.793680077 [zed2.zed_node] [INFO]  * [DYN] Depth Texture Confidence: 100
[zed_wrapper-2] 1636996692.793701807 [zed2.zed_node] [INFO]  * Depth QoS History: KEEP_LAST
[zed_wrapper-2] 1636996692.793725251 [zed2.zed_node] [INFO]  * Depth QoS History depth: 1
[zed_wrapper-2] 1636996692.793747769 [zed2.zed_node] [INFO]  * Depth QoS Reliability: RELIABLE
[zed_wrapper-2] 1636996692.793772587 [zed2.zed_node] [INFO]  * Depth QoS Durability: VOLATILE
[zed_wrapper-2] 1636996692.793779909 [zed2.zed_node] [INFO] *** POSITIONAL TRACKING parameters ***
[zed_wrapper-2] 1636996692.793812937 [zed2.zed_node] [INFO]  * Positional tracking enabled: TRUE
[zed_wrapper-2] 1636996692.793837734 [zed2.zed_node] [INFO]  * Base frame id: base_link
[zed_wrapper-2] 1636996692.793861083 [zed2.zed_node] [INFO]  * Map frame id: map
[zed_wrapper-2] 1636996692.793884748 [zed2.zed_node] [INFO]  * Odometry frame id: odom
[zed_wrapper-2] 1636996692.793908534 [zed2.zed_node] [INFO]  * Broadcast Odometry TF: TRUE
[zed_wrapper-2] 1636996692.793932951 [zed2.zed_node] [INFO]  * Broadcast Pose TF: TRUE
[zed_wrapper-2] 1636996692.793957029 [zed2.zed_node] [INFO]  * Broadcast Static IMU TF [not for ZED]: TRUE
[zed_wrapper-2] 1636996692.793982740 [zed2.zed_node] [INFO]  * [DYN] Path publishing rate: 2
[zed_wrapper-2] 1636996692.794006587 [zed2.zed_node] [INFO]  * Path history lenght: -1
[zed_wrapper-2] 1636996692.794031323 [zed2.zed_node] [INFO]  * Initial pose: [0,0,0,0,0,0,]
[zed_wrapper-2] 1636996692.794052945 [zed2.zed_node] [INFO]  * Area Memory: TRUE
[zed_wrapper-2] 1636996692.794077076 [zed2.zed_node] [INFO]  * Area Memory DB: 
[zed_wrapper-2] 1636996692.794102084 [zed2.zed_node] [INFO]  * IMU Fusion [not for ZED]: TRUE
[zed_wrapper-2] 1636996692.794126637 [zed2.zed_node] [INFO]  * Floor Alignment: FALSE
[zed_wrapper-2] 1636996692.794157445 [zed2.zed_node] [INFO]  * Init Odometry with first valid pose data: TRUE
[zed_wrapper-2] 1636996692.794181735 [zed2.zed_node] [INFO]  * 2D mode: FALSE
[zed_wrapper-2] 1636996692.794206089 [zed2.zed_node] [INFO]  * Pose/Odometry QoS History: KEEP_LAST
[zed_wrapper-2] 1636996692.794229536 [zed2.zed_node] [INFO]  * Pose/Odometry QoS History depth: 1
[zed_wrapper-2] 1636996692.794253928 [zed2.zed_node] [INFO]  * Pose/Odometry QoS Reliability: RELIABLE
[zed_wrapper-2] 1636996692.794284144 [zed2.zed_node] [INFO]  * Pose/Odometry QoS Durability: VOLATILE
[zed_wrapper-2] 1636996692.794294990 [zed2.zed_node] [INFO] *** SENSORS STACK parameters ***
[zed_wrapper-2] 1636996692.794308956 [zed2.zed_node] [INFO]  * Sensors Camera Sync: FALSE
[zed_wrapper-2] 1636996692.794335798 [zed2.zed_node] [INFO]  * Sensors publishing rate: 200 Hz
[zed_wrapper-2] 1636996692.794358716 [zed2.zed_node] [INFO]  * Sensors QoS History: KEEP_LAST
[zed_wrapper-2] 1636996692.794383599 [zed2.zed_node] [INFO]  * Sensors QoS History depth: 1
[zed_wrapper-2] 1636996692.794409894 [zed2.zed_node] [INFO]  * Sensors QoS Reliability: RELIABLE
[zed_wrapper-2] 1636996692.794434689 [zed2.zed_node] [INFO]  * Sensors QoS Durability: VOLATILE
[zed_wrapper-2] 1636996692.794442074 [zed2.zed_node] [INFO] *** Spatial Mapping parameters ***
[zed_wrapper-2] 1636996692.794462434 [zed2.zed_node] [INFO]  * Spatial Mapping Enabled: FALSE
[zed_wrapper-2] 1636996692.794489777 [zed2.zed_node] [INFO]  * Spatial Mapping resolution [m]: 0.1
[zed_wrapper-2] 1636996692.794514857 [zed2.zed_node] [INFO]  * 3D Max Mapping range [m]: 20
[zed_wrapper-2] 1636996692.794540714 [zed2.zed_node] [INFO]  * Map publishing rate [Hz]: 0.5
[zed_wrapper-2] 1636996692.794564934 [zed2.zed_node] [INFO]  * Sensors QoS History: KEEP_LAST
[zed_wrapper-2] 1636996692.794591820 [zed2.zed_node] [INFO]  * Sensors QoS History depth: 1
[zed_wrapper-2] 1636996692.794619419 [zed2.zed_node] [INFO]  * Sensors QoS Reliability: RELIABLE
[zed_wrapper-2] 1636996692.794645443 [zed2.zed_node] [INFO]  * Sensors QoS Durability: VOLATILE
[zed_wrapper-2] 1636996692.794652773 [zed2.zed_node] [INFO] *** OBJECT DETECTION parameters ***
[zed_wrapper-2] 1636996692.794673841 [zed2.zed_node] [INFO]  * Object Detection enabled: FALSE
[zed_wrapper-2] 1636996692.794701794 [zed2.zed_node] [INFO]  * OD min. confidence: 50
[zed_wrapper-2] 1636996692.794728874 [zed2.zed_node] [INFO]  * Object Detection model: 0 - MULTI CLASS BOX FAST
[zed_wrapper-2] 1636996692.794753466 [zed2.zed_node] [INFO]  * MultiClassBox people: TRUE
[zed_wrapper-2] 1636996692.794780011 [zed2.zed_node] [INFO]  * MultiClassBox vehicles: TRUE
[zed_wrapper-2] 1636996692.794807323 [zed2.zed_node] [INFO]  * MultiClassBox bags: TRUE
[zed_wrapper-2] 1636996692.794846741 [zed2.zed_node] [INFO]  * MultiClassBox animals: TRUE
[zed_wrapper-2] 1636996692.794879038 [zed2.zed_node] [INFO]  * MultiClassBox electronics: TRUE
[zed_wrapper-2] 1636996692.794907834 [zed2.zed_node] [INFO]  * MultiClassBox fruits and vegetables: TRUE
[zed_wrapper-2] 1636996692.794936043 [zed2.zed_node] [INFO]  * Skeleton fitting: FALSE
[zed_wrapper-2] 1636996692.794963100 [zed2.zed_node] [INFO]  * Obj. Det. QoS History: KEEP_LAST
[zed_wrapper-2] 1636996692.794991226 [zed2.zed_node] [INFO]  * Obj. Det. QoS History depth: 1
[zed_wrapper-2] 1636996692.795019913 [zed2.zed_node] [INFO]  * Obj. Det. QoS Reliability: RELIABLE
[zed_wrapper-2] 1636996692.795048612 [zed2.zed_node] [INFO]  * Obj. Det. QoS Durability: VOLATILE
[zed_wrapper-2] 1636996692.795092945 [zed2.zed_node] [INFO] *** SERVICES ***
[zed_wrapper-2] 1636996692.795372864 [zed2.zed_node] [INFO]  * '/zed2/zed_node/reset_odometry'
[zed_wrapper-2] 1636996692.795539564 [zed2.zed_node] [INFO]  * '/zed2/zed_node/reset_pos_tracking'
[zed_wrapper-2] 1636996692.795796881 [zed2.zed_node] [INFO]  * '/zed2/zed_node/set_pose'
[zed_wrapper-2] 1636996692.795982901 [zed2.zed_node] [INFO]  * '/zed2/zed_node/enable_obj_det'
[zed_wrapper-2] 1636996692.796128220 [zed2.zed_node] [INFO]  * '/zed2/zed_node/enable_mapping'
[zed_wrapper-2] 1636996692.796310430 [zed2.zed_node] [INFO]  * '/zed2/zed_node/start_svo_rec'
[zed_wrapper-2] 1636996692.796457547 [zed2.zed_node] [INFO]  * '/zed2/zed_node/stop_svo_rec'
[zed_wrapper-2] 1636996692.796599792 [zed2.zed_node] [INFO]  * '/zed2/zed_node/toggle_svo_pause'
[zed_wrapper-2] 1636996692.796613802 [zed2.zed_node] [INFO] ***** STARTING CAMERA *****
[zed_wrapper-2] 1636996692.796619107 [zed2.zed_node] [INFO] SDK Version: 3.5.1 - Build 26368_03ef6906
[zed_wrapper-2] 1636996692.797929187 [zed2.zed_node] [INFO] *** CAMERA OPENING ***
[rviz2-3] 1636996693.267196247 [rviz2] [INFO] Stereo is NOT SUPPORTED
[rviz2-3] 1636996693.267283900 [rviz2] [INFO] OpenGl version: 4.6 (GLSL 4.6)
[rviz2-3] 1636996693.285741263 [rviz2] [INFO] Stereo is NOT SUPPORTED
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[zed_wrapper-2] 1636996693.399577264 [zed2.zed_node] [WARN] Error opening camera: CAMERA NOT DETECTED
[zed_wrapper-2] 1636996693.399613872 [zed2.zed_node] [INFO] Please verify the USB3 connection
[rviz2-3] 1636996693.430213915 [rviz2] [INFO] Stereo is NOT SUPPORTED
[rviz2-3] 1636996693.447268157 [rviz2] [INFO] Stereo is NOT SUPPORTED
[rviz2-3] 1636996693.466859953 [rviz2] [INFO] Stereo is NOT SUPPORTED
[rviz2-3] 1636996693.482294576 [rviz2] [INFO] Stereo is NOT SUPPORTED
[rviz2-3] Parsing robot urdf xml string.
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp

### ZED Camera model

ZED2

### Environment

```shell
OS:Linux
```

**Comment by Myzhar** [comment]
It's not a bug. It happens when RVIZ2 starts and the ZED node is not yet ready.
In this case Rviz issues a warning about missing frames, but it starts working correctly as soon as the ZED node starts broadcasting the TF frames

**Comment by an99990** [comment]
but i dont see anything in rviz, i keep getting this warning indefinitely 
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3] at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.11/src/buffer_core.cpp

**Comment by Myzhar** [comment]
Sorry, I missed the following two important log lines:
```
[zed_wrapper-2] 1636996693.399577264 [zed2.zed_node] [WARN] Error opening camera: CAMERA NOT DETECTED
[zed_wrapper-2] 1636996693.399613872 [zed2.zed_node] [INFO] Please verify the USB3 connection
```
Can you correctly open the camera by using one of our tools? 
For example, try to launch `ZED_Explorer`

**Comment by an99990** [comment]
The things is that i want out a svo file in common.yaml. so even if I'm just reading a video, i need to have the zed plugged in ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Myzhar** [comment]
No, you don't. But you need to set up correctly the input:
`$ ros2 launch zed_display_rviz2 display_zed2.launch.py :=<SVO_filename>`

**Comment by an99990** [comment]
i get this error when i try your command line
bash: syntax error near unexpected token `newline'
i type in
ros2 launch zed_display_rviz2 display_zed2.launch.py :=<svo/ccw2.svo>

**Comment by Myzhar** [comment]
You must remove the brackets:
`ros2 launch zed_display_rviz2 display_zed2.launch.py svo_path:=svo/ccw2.svo`

**Comment by an99990** [comment]
Thank you it worked :)
