### ISSUE TITLE
Service Call - Set Pose - Fails

### ISSUE THREAD

**Issue by THLL245** [stereolabs/zed-ros2-wrapper#86]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Attempting to use AMCL node but realized the ZED holds its place and any AMCL transforms are worthless because ZED holds its original pose (let me know if there is a way around that please). So needed to set its pose manually using the ZED set pose service call. Realized it works maybe 1-3 times before failing.

Tested without running any other nodes and same results 

### Steps to Reproduce

1. ros2 launch zed_wrapper zed2i.launch.py
2. ros2 service call /zed2i/zed_node/set_pose zed_interfaces/srv/SetPose "{pos: [1.204, -0.46, 0.0], orient: [1.0,-8.2,0.0]}"  (Can be any positions)
3. Do this 1-3 times before you don't get a responder message and unable to set any poses again
...

### Expected Result

Expected a change in pose

### Actual Result

No responder, no pose change

### ZED Camera model

ZED2i

### Environment

```shell
Ubuntu 20.04
Jetson Xaiver AGX
ROS2 Foxy
ZED SDK JP45 3.7
```

### Anything else?

Is it possible to use AMCL with the zed without setting the poses like this manually?

**Comment by Myzhar** [comment]
@THLL245 can you try the latest fix to the `set_pose` service?
