### ISSUE TITLE
Branch change needed

### ISSUE THREAD

**Issue by levmarki** [stereolabs/zed-ros2-wrapper#97]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hello,
we installed the ZED ROS wrapper on the Jetson NX and faced few bugs in instructions.
First of all, the row
`$ git clone https://github.com/stereolabs/zed-ros2-wrapper.git
`
didn't work for us for future install. When we added `--recursive` and changed branch in checkout to eloquent the installation worked better.

In addition, we needed to add 
`export OPENBLAS_CORETYPE=ARMV8 `
to run it correctly.

### Steps to Reproduce

Simple follow the instructions in **eloquent** branch and the error will be reproduced.

### Expected Result

The ROS wrapper to be installed and ready.

### Actual Result

Colcon build fails or installation fails.

### ZED Camera model

ZED Mini

### Environment

```shell
OS: Ubuntu 18.04
Platform: Jetson NX
JetPack 4.5.1
```

**Comment by Myzhar** [comment]
I'm sorry, but the ROS2 Eloquent distribution [reached EOL in November 2020](https://docs.ros.org/en/rolling/Releases.html) consequently the Eloquent branch is no more maintained.
We keep it in the repository for who needs it. We update the README consequently.
